/**
 * Email Signature Template System — 100 professionally distinct templates
 *
 * Each template has unique visual DNA: different typography, colour palette,
 * layout, accent treatment, divider style, contact style, and social style.
 * No two templates look the same.
 */

export type TemplateCategory =
  | 'corporate' | 'modern' | 'minimal' | 'creative' | 'luxury'
  | 'tech' | 'healthcare' | 'legal' | 'realestate' | 'education'
  | 'smallbiz' | 'freelancer' | 'consultant' | 'sales' | 'executive' | 'personal';

export type SignatureLayout = 'horizontal' | 'vertical' | 'compact' | 'banner' | 'card' | 'split';
export type ColorScheme = 'light' | 'dark' | 'accent' | 'minimal' | 'gradient';
export type AccentBar = 'left' | 'top' | 'bottom' | 'none';
export type PhotoShape = 'circle' | 'square' | 'none';

export interface SignatureTemplate {
  id: string;
  name: string;
  category: TemplateCategory;
  description: string;
  layout: SignatureLayout;
  colorScheme: ColorScheme;
  accentBar?: AccentBar;
  photoShape?: PhotoShape;

  primaryColor: string;
  accentColor: string;
  backgroundColor: string;
  textColor: string;
  mutedColor: string;
  fontFamily: string;
  nameFontFamily?: string;
  borderRadius: number;
  borderStyle: 'none' | 'solid' | 'double' | 'left-rule' | 'top-rule' | 'bottom-rule';
  dividerStyle: 'none' | 'thin' | 'bold' | 'dotted' | 'gradient';
  contactStyle: 'icons' | 'labels' | 'pills' | 'inline' | 'stacked';
  socialStyle: 'icons' | 'text' | 'buttons' | 'none';
  shadow: 'none' | 'soft' | 'strong';
}

// ─── Full template definitions (100 templates) ────────────────────────────────

export const SIGNATURE_TEMPLATES: SignatureTemplate[] = [

  // ── CORPORATE (8) ──────────────────────────────────────────────────────────
  {
    id: 'corp-h-light', name: 'Corporate Classic', category: 'corporate',
    description: 'Navy left-rule, square photo, Arial — the gold standard for enterprise email',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'square',
    primaryColor: '#172554', accentColor: '#2563eb', backgroundColor: '#ffffff',
    textColor: '#111827', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'corp-h-dark', name: 'Corporate Dark', category: 'corporate',
    description: 'Deep navy background, white text, electric blue accents',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'square',
    primaryColor: '#e2e8f0', accentColor: '#60a5fa', backgroundColor: '#0f172a',
    textColor: '#e2e8f0', mutedColor: '#94a3b8', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'corp-v-light', name: 'Corporate Vertical', category: 'corporate',
    description: 'Centred vertical layout with top accent bar and circular photo',
    layout: 'vertical', colorScheme: 'light', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#172554', accentColor: '#2563eb', backgroundColor: '#f8fafc',
    textColor: '#1e293b', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'top-rule', dividerStyle: 'thin',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'soft',
  },
  {
    id: 'corp-c-light', name: 'Corporate Compact', category: 'corporate',
    description: 'Single-line compact format — name, title, contacts separated by pipes',
    layout: 'compact', colorScheme: 'light', accentBar: 'none', photoShape: 'none',
    primaryColor: '#172554', accentColor: '#2563eb', backgroundColor: '#ffffff',
    textColor: '#374151', mutedColor: '#9ca3af', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'corp-card-light', name: 'Corporate Card', category: 'corporate',
    description: 'Bordered card with subtle shadow, blue accent border on photo',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#172554', accentColor: '#2563eb', backgroundColor: '#ffffff',
    textColor: '#1e293b', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 8, borderStyle: 'solid', dividerStyle: 'thin',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'corp-split-dark', name: 'Corporate Split Dark', category: 'corporate',
    description: 'Two-column split: dark navy left panel, white right panel',
    layout: 'split', colorScheme: 'dark', accentBar: 'none', photoShape: 'square',
    primaryColor: '#ffffff', accentColor: '#3b82f6', backgroundColor: '#0f172a',
    textColor: '#e2e8f0', mutedColor: '#94a3b8', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'corp-b-light', name: 'Corporate Banner', category: 'corporate',
    description: 'Full-width blue header banner with white name, contacts below',
    layout: 'banner', colorScheme: 'light', accentBar: 'bottom', photoShape: 'circle',
    primaryColor: '#172554', accentColor: '#2563eb', backgroundColor: '#ffffff',
    textColor: '#374151', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'bottom-rule', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'corp-b-dark', name: 'Corporate Banner Dark', category: 'corporate',
    description: 'Dark banner header, clean white contact row below',
    layout: 'banner', colorScheme: 'dark', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#e2e8f0', accentColor: '#60a5fa', backgroundColor: '#1e293b',
    textColor: '#e2e8f0', mutedColor: '#94a3b8', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'icons', shadow: 'none',
  },

  // ── MODERN (8) ─────────────────────────────────────────────────────────────
  {
    id: 'mod-h-light', name: 'Modern Horizontal', category: 'modern',
    description: 'Inter font, cyan accent, no border — clean and contemporary',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#0f172a', accentColor: '#06b6d4', backgroundColor: '#f8fafc',
    textColor: '#0f172a', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'none', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'mod-h-dark', name: 'Modern Dark', category: 'modern',
    description: 'Slate-900 background, cyan glow accents, Inter typeface',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#f1f5f9', accentColor: '#22d3ee', backgroundColor: '#0f172a',
    textColor: '#e2e8f0', mutedColor: '#94a3b8', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'none', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'mod-v-light', name: 'Modern Vertical', category: 'modern',
    description: 'Centred vertical with left accent rule, Inter, teal highlights',
    layout: 'vertical', colorScheme: 'light', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#0f172a', accentColor: '#06b6d4', backgroundColor: '#ffffff',
    textColor: '#334155', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'dotted',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'mod-card-light', name: 'Modern Card', category: 'modern',
    description: 'Rounded card, cyan photo border, pill-style contact links',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#0f172a', accentColor: '#06b6d4', backgroundColor: '#f0f9ff',
    textColor: '#0f172a', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 12, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'mod-split-light', name: 'Modern Split', category: 'modern',
    description: 'Cyan left panel, white right — bold name on colour, contacts on white',
    layout: 'split', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#0f172a', accentColor: '#06b6d4', backgroundColor: '#ffffff',
    textColor: '#0f172a', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'mod-c-dark', name: 'Modern Compact Dark', category: 'modern',
    description: 'Ultra-slim dark compact, cyan name, pipe-separated contacts',
    layout: 'compact', colorScheme: 'dark', accentBar: 'none', photoShape: 'none',
    primaryColor: '#f1f5f9', accentColor: '#22d3ee', backgroundColor: '#0f172a',
    textColor: '#cbd5e1', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'mod-b-gradient', name: 'Modern Gradient Banner', category: 'modern',
    description: 'Cyan-to-blue gradient header, white name, clean contact row',
    layout: 'banner', colorScheme: 'gradient', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#0f172a', accentColor: '#06b6d4', backgroundColor: '#f8fafc',
    textColor: '#0f172a', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 8, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'icons', shadow: 'soft',
  },
  {
    id: 'mod-v-dark', name: 'Modern Vertical Dark', category: 'modern',
    description: 'Dark vertical centred layout, glowing cyan accents, Inter',
    layout: 'vertical', colorScheme: 'dark', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#f1f5f9', accentColor: '#22d3ee', backgroundColor: '#0f172a',
    textColor: '#e2e8f0', mutedColor: '#94a3b8', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'top-rule', dividerStyle: 'bold',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'none',
  },

  // ── MINIMAL (6) ────────────────────────────────────────────────────────────
  {
    id: 'min-h-light', name: 'Minimal Horizontal', category: 'minimal',
    description: 'Pure white, no photo, thin grey rule — absolute simplicity',
    layout: 'horizontal', colorScheme: 'minimal', accentBar: 'none', photoShape: 'none',
    primaryColor: '#111827', accentColor: '#9ca3af', backgroundColor: '#ffffff',
    textColor: '#111827', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'thin',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'min-h-dark', name: 'Minimal Dark', category: 'minimal',
    description: 'Near-black background, white name, grey contacts — stark and elegant',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'none', photoShape: 'none',
    primaryColor: '#f9fafb', accentColor: '#d1d5db', backgroundColor: '#111827',
    textColor: '#f9fafb', mutedColor: '#9ca3af', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'thin',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'min-v-light', name: 'Minimal Vertical', category: 'minimal',
    description: 'Centred vertical, left rule, no photo, dotted divider',
    layout: 'vertical', colorScheme: 'minimal', accentBar: 'left', photoShape: 'none',
    primaryColor: '#111827', accentColor: '#6b7280', backgroundColor: '#ffffff',
    textColor: '#374151', mutedColor: '#9ca3af', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'dotted',
    contactStyle: 'stacked', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'min-c-light', name: 'Minimal Compact', category: 'minimal',
    description: 'One line, everything inline — the smallest possible footprint',
    layout: 'compact', colorScheme: 'minimal', accentBar: 'none', photoShape: 'none',
    primaryColor: '#111827', accentColor: '#6b7280', backgroundColor: '#ffffff',
    textColor: '#374151', mutedColor: '#9ca3af', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'none', shadow: 'none',
  },
  {
    id: 'min-card-light', name: 'Minimal Card', category: 'minimal',
    description: 'Light grey card, circle photo, no colour — refined restraint',
    layout: 'card', colorScheme: 'minimal', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#111827', accentColor: '#6b7280', backgroundColor: '#f9fafb',
    textColor: '#1f2937', mutedColor: '#9ca3af', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 8, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'icons', shadow: 'soft',
  },
  {
    id: 'min-split-light', name: 'Minimal Split', category: 'minimal',
    description: 'Pale grey left panel, white right — monochrome two-column',
    layout: 'split', colorScheme: 'minimal', accentBar: 'none', photoShape: 'none',
    primaryColor: '#111827', accentColor: '#6b7280', backgroundColor: '#f3f4f6',
    textColor: '#374151', mutedColor: '#9ca3af', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'stacked', socialStyle: 'text', shadow: 'none',
  },

  // ── CREATIVE (7) ───────────────────────────────────────────────────────────
  {
    id: 'cre-h-light', name: 'Creative Horizontal', category: 'creative',
    description: 'Purple + orange duo-tone, Inter, bold left rule, circle photo',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#581c87', accentColor: '#f97316', backgroundColor: '#fff7ed',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'none',
    contactStyle: 'labels', socialStyle: 'buttons', shadow: 'none',
  },
  {
    id: 'cre-h-dark', name: 'Creative Dark', category: 'creative',
    description: 'Deep purple background, orange fire accents, Inter',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#f3e8ff', accentColor: '#fb923c', backgroundColor: '#1e1b4b',
    textColor: '#f3e8ff', mutedColor: '#a78bfa', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'buttons', shadow: 'none',
  },
  {
    id: 'cre-v-gradient', name: 'Creative Gradient', category: 'creative',
    description: 'Purple-to-orange gradient vertical, white text, bold presence',
    layout: 'vertical', colorScheme: 'gradient', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#581c87', accentColor: '#f97316', backgroundColor: '#fff7ed',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 8, borderStyle: 'top-rule', dividerStyle: 'gradient',
    contactStyle: 'stacked', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'cre-card-light', name: 'Creative Card', category: 'creative',
    description: 'Warm cream card, purple name, orange social buttons',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#581c87', accentColor: '#f97316', backgroundColor: '#fdf4ff',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 12, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'cre-split-dark', name: 'Creative Split Dark', category: 'creative',
    description: 'Purple left panel, dark right — dramatic creative contrast',
    layout: 'split', colorScheme: 'dark', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#f3e8ff', accentColor: '#fb923c', backgroundColor: '#1e1b4b',
    textColor: '#f3e8ff', mutedColor: '#a78bfa', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'cre-b-gradient', name: 'Creative Banner', category: 'creative',
    description: 'Gradient banner header, warm body, creative energy',
    layout: 'banner', colorScheme: 'gradient', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#581c87', accentColor: '#f97316', backgroundColor: '#fff7ed',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 8, borderStyle: 'none', dividerStyle: 'gradient',
    contactStyle: 'inline', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'cre-c-light', name: 'Creative Compact', category: 'creative',
    description: 'Compact purple/orange, left rule, inline contacts',
    layout: 'compact', colorScheme: 'light', accentBar: 'left', photoShape: 'none',
    primaryColor: '#581c87', accentColor: '#f97316', backgroundColor: '#ffffff',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },

  // ── LUXURY (7) ─────────────────────────────────────────────────────────────
  {
    id: 'lux-h-light', name: 'Luxury Classic', category: 'luxury',
    description: 'Georgia serif, gold accent, bottom rule — timeless elegance',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'bottom', photoShape: 'circle',
    primaryColor: '#111111', accentColor: '#c9a227', backgroundColor: '#fbfaf7',
    textColor: '#171717', mutedColor: '#737373', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'bottom-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'lux-h-dark', name: 'Luxury Dark', category: 'luxury',
    description: 'Charcoal background, gold name, serif — opulent and authoritative',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'bottom', photoShape: 'circle',
    primaryColor: '#fef3c7', accentColor: '#d97706', backgroundColor: '#1c1917',
    textColor: '#fef3c7', mutedColor: '#a8a29e', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'bottom-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'lux-v-light', name: 'Luxury Vertical', category: 'luxury',
    description: 'Centred serif vertical, gold left rule, square photo',
    layout: 'vertical', colorScheme: 'light', accentBar: 'left', photoShape: 'square',
    primaryColor: '#111111', accentColor: '#c9a227', backgroundColor: '#fbfaf7',
    textColor: '#171717', mutedColor: '#737373', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'dotted',
    contactStyle: 'stacked', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'lux-card-light', name: 'Luxury Card', category: 'luxury',
    description: 'Cream card, gold photo ring, serif name — boutique hotel feel',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#111111', accentColor: '#c9a227', backgroundColor: '#fffbeb',
    textColor: '#171717', mutedColor: '#737373', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 8, borderStyle: 'solid', dividerStyle: 'thin',
    contactStyle: 'pills', socialStyle: 'text', shadow: 'soft',
  },
  {
    id: 'lux-split-dark', name: 'Luxury Split Dark', category: 'luxury',
    description: 'Black left panel, cream right — high-fashion editorial split',
    layout: 'split', colorScheme: 'dark', accentBar: 'none', photoShape: 'square',
    primaryColor: '#fef3c7', accentColor: '#d97706', backgroundColor: '#1c1917',
    textColor: '#fef3c7', mutedColor: '#a8a29e', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'stacked', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'lux-b-light', name: 'Luxury Banner', category: 'luxury',
    description: 'Gold gradient banner, serif name in white, cream body',
    layout: 'banner', colorScheme: 'light', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#111111', accentColor: '#c9a227', backgroundColor: '#fbfaf7',
    textColor: '#171717', mutedColor: '#737373', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'top-rule', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'lux-c-light', name: 'Luxury Compact', category: 'luxury',
    description: 'Compact serif, gold name, understated pipe separators',
    layout: 'compact', colorScheme: 'light', accentBar: 'none', photoShape: 'none',
    primaryColor: '#111111', accentColor: '#c9a227', backgroundColor: '#fbfaf7',
    textColor: '#171717', mutedColor: '#737373', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },

  // ── TECH (7) ───────────────────────────────────────────────────────────────
  {
    id: 'tech-h-dark', name: 'Tech Dark', category: 'tech',
    description: 'Near-black background, sky-blue accents, monospace feel',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'square',
    primaryColor: '#f0f9ff', accentColor: '#38bdf8', backgroundColor: '#020617',
    textColor: '#e0f2fe', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'tech-h-light', name: 'Tech Light', category: 'tech',
    description: 'White background, sky-blue accents, sharp square photo',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'square',
    primaryColor: '#020617', accentColor: '#38bdf8', backgroundColor: '#f0f9ff',
    textColor: '#0f172a', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'tech-v-dark', name: 'Tech Vertical Dark', category: 'tech',
    description: 'Dark vertical, top blue rule, circle photo with glow',
    layout: 'vertical', colorScheme: 'dark', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#f0f9ff', accentColor: '#38bdf8', backgroundColor: '#020617',
    textColor: '#e0f2fe', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'top-rule', dividerStyle: 'bold',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'tech-card-dark', name: 'Tech Card Dark', category: 'tech',
    description: 'Dark card, sky-blue photo border, pill contacts',
    layout: 'card', colorScheme: 'dark', accentBar: 'none', photoShape: 'square',
    primaryColor: '#f0f9ff', accentColor: '#38bdf8', backgroundColor: '#0c1a2e',
    textColor: '#e0f2fe', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 8, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'strong',
  },
  {
    id: 'tech-split-dark', name: 'Tech Split Dark', category: 'tech',
    description: 'Dark blue left, charcoal right — developer aesthetic',
    layout: 'split', colorScheme: 'dark', accentBar: 'none', photoShape: 'square',
    primaryColor: '#f0f9ff', accentColor: '#38bdf8', backgroundColor: '#020617',
    textColor: '#e0f2fe', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'tech-c-dark', name: 'Tech Compact Dark', category: 'tech',
    description: 'Compact dark, sky-blue name, inline contacts',
    layout: 'compact', colorScheme: 'dark', accentBar: 'none', photoShape: 'none',
    primaryColor: '#f0f9ff', accentColor: '#38bdf8', backgroundColor: '#020617',
    textColor: '#e0f2fe', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'tech-b-gradient', name: 'Tech Gradient Banner', category: 'tech',
    description: 'Dark-to-blue gradient banner, white name, clean body',
    layout: 'banner', colorScheme: 'gradient', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#020617', accentColor: '#38bdf8', backgroundColor: '#f0f9ff',
    textColor: '#0f172a', mutedColor: '#64748b', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 8, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'icons', shadow: 'soft',
  },

  // ── HEALTHCARE (5) ─────────────────────────────────────────────────────────
  {
    id: 'hc-h-light', name: 'Healthcare Classic', category: 'healthcare',
    description: 'Teal accents on white, circle photo, clean and clinical',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#064e3b', accentColor: '#14b8a6', backgroundColor: '#f0fdfa',
    textColor: '#134e4a', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'hc-h-dark', name: 'Healthcare Dark', category: 'healthcare',
    description: 'Deep teal background, white text — authoritative clinical dark',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#ccfbf1', accentColor: '#2dd4bf', backgroundColor: '#042f2e',
    textColor: '#ccfbf1', mutedColor: '#5eead4', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'hc-v-light', name: 'Healthcare Vertical', category: 'healthcare',
    description: 'Centred vertical, teal top rule, circle photo',
    layout: 'vertical', colorScheme: 'light', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#064e3b', accentColor: '#14b8a6', backgroundColor: '#f0fdfa',
    textColor: '#134e4a', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'top-rule', dividerStyle: 'thin',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'soft',
  },
  {
    id: 'hc-card-light', name: 'Healthcare Card', category: 'healthcare',
    description: 'Mint card, teal photo border, pill contacts',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#064e3b', accentColor: '#14b8a6', backgroundColor: '#f0fdfa',
    textColor: '#134e4a', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 12, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'hc-c-light', name: 'Healthcare Compact', category: 'healthcare',
    description: 'Compact teal, inline contacts, no photo',
    layout: 'compact', colorScheme: 'light', accentBar: 'none', photoShape: 'none',
    primaryColor: '#064e3b', accentColor: '#14b8a6', backgroundColor: '#ffffff',
    textColor: '#134e4a', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },

  // ── LEGAL (5) ──────────────────────────────────────────────────────────────
  {
    id: 'leg-h-light', name: 'Legal Classic', category: 'legal',
    description: 'Georgia serif, amber bottom rule, square photo — traditional chambers',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'bottom', photoShape: 'square',
    primaryColor: '#111827', accentColor: '#b45309', backgroundColor: '#ffffff',
    textColor: '#111827', mutedColor: '#6b7280', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'bottom-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'leg-h-dark', name: 'Legal Dark', category: 'legal',
    description: 'Dark legal, amber accents, serif — gravitas and authority',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'bottom', photoShape: 'square',
    primaryColor: '#fef3c7', accentColor: '#d97706', backgroundColor: '#1c1917',
    textColor: '#fef3c7', mutedColor: '#a8a29e', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'bottom-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'leg-v-light', name: 'Legal Vertical', category: 'legal',
    description: 'Centred serif vertical, amber left rule, square photo',
    layout: 'vertical', colorScheme: 'light', accentBar: 'left', photoShape: 'square',
    primaryColor: '#111827', accentColor: '#b45309', backgroundColor: '#ffffff',
    textColor: '#111827', mutedColor: '#6b7280', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'dotted',
    contactStyle: 'stacked', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'leg-card-light', name: 'Legal Card', category: 'legal',
    description: 'Ivory card, amber photo border, serif name',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'square',
    primaryColor: '#111827', accentColor: '#b45309', backgroundColor: '#fffbeb',
    textColor: '#111827', mutedColor: '#6b7280', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 4, borderStyle: 'solid', dividerStyle: 'thin',
    contactStyle: 'pills', socialStyle: 'text', shadow: 'soft',
  },
  {
    id: 'leg-c-light', name: 'Legal Compact', category: 'legal',
    description: 'Compact serif, amber name, minimal footprint',
    layout: 'compact', colorScheme: 'minimal', accentBar: 'none', photoShape: 'none',
    primaryColor: '#111827', accentColor: '#b45309', backgroundColor: '#ffffff',
    textColor: '#374151', mutedColor: '#9ca3af', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'none', shadow: 'none',
  },

  // ── REAL ESTATE (5) ────────────────────────────────────────────────────────
  {
    id: 're-h-light', name: 'Real Estate Classic', category: 'realestate',
    description: 'Navy + red, circle photo, left rule — trusted agent look',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#1e3a8a', accentColor: '#dc2626', backgroundColor: '#ffffff',
    textColor: '#111827', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 're-h-dark', name: 'Real Estate Dark', category: 'realestate',
    description: 'Dark navy, red accents — premium property feel',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#dbeafe', accentColor: '#f87171', backgroundColor: '#1e3a8a',
    textColor: '#dbeafe', mutedColor: '#93c5fd', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 're-v-light', name: 'Real Estate Vertical', category: 'realestate',
    description: 'Centred vertical, top navy rule, circle photo',
    layout: 'vertical', colorScheme: 'light', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#1e3a8a', accentColor: '#dc2626', backgroundColor: '#eff6ff',
    textColor: '#1e3a8a', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'top-rule', dividerStyle: 'thin',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'soft',
  },
  {
    id: 're-card-light', name: 'Real Estate Card', category: 'realestate',
    description: 'Blue card, red photo ring, pill contacts',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#1e3a8a', accentColor: '#dc2626', backgroundColor: '#eff6ff',
    textColor: '#1e3a8a', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 8, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 're-b-light', name: 'Real Estate Banner', category: 'realestate',
    description: 'Navy banner, white name, red accent contacts',
    layout: 'banner', colorScheme: 'light', accentBar: 'bottom', photoShape: 'circle',
    primaryColor: '#1e3a8a', accentColor: '#dc2626', backgroundColor: '#ffffff',
    textColor: '#374151', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'bottom-rule', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'icons', shadow: 'none',
  },

  // ── EDUCATION (5) ──────────────────────────────────────────────────────────
  {
    id: 'edu-h-light', name: 'Education Classic', category: 'education',
    description: 'Royal blue + amber, circle photo, left rule — academic authority',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#1e3a8a', accentColor: '#f59e0b', backgroundColor: '#f8fafc',
    textColor: '#111827', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'edu-h-dark', name: 'Education Dark', category: 'education',
    description: 'Dark blue, amber accents — prestigious institution feel',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#dbeafe', accentColor: '#fbbf24', backgroundColor: '#1e3a8a',
    textColor: '#dbeafe', mutedColor: '#93c5fd', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'edu-v-light', name: 'Education Vertical', category: 'education',
    description: 'Centred vertical, amber top rule, circle photo',
    layout: 'vertical', colorScheme: 'light', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#1e3a8a', accentColor: '#f59e0b', backgroundColor: '#f8fafc',
    textColor: '#1e3a8a', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'top-rule', dividerStyle: 'thin',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'soft',
  },
  {
    id: 'edu-card-light', name: 'Education Card', category: 'education',
    description: 'Blue card, amber photo ring, pill contacts',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#1e3a8a', accentColor: '#f59e0b', backgroundColor: '#eff6ff',
    textColor: '#1e3a8a', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 8, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'edu-c-light', name: 'Education Compact', category: 'education',
    description: 'Compact blue/amber, inline contacts, no photo',
    layout: 'compact', colorScheme: 'light', accentBar: 'none', photoShape: 'none',
    primaryColor: '#1e3a8a', accentColor: '#f59e0b', backgroundColor: '#ffffff',
    textColor: '#111827', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },

  // ── SMALL BUSINESS (5) ─────────────────────────────────────────────────────
  {
    id: 'sb-h-light', name: 'Small Biz Classic', category: 'smallbiz',
    description: 'Forest green + lime, circle photo, friendly and approachable',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#14532d', accentColor: '#22c55e', backgroundColor: '#f7fee7',
    textColor: '#1f2937', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'sb-h-dark', name: 'Small Biz Dark', category: 'smallbiz',
    description: 'Dark green, lime accents — bold small business energy',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#dcfce7', accentColor: '#4ade80', backgroundColor: '#14532d',
    textColor: '#dcfce7', mutedColor: '#86efac', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'sb-v-light', name: 'Small Biz Vertical', category: 'smallbiz',
    description: 'Centred vertical, green top rule, circle photo',
    layout: 'vertical', colorScheme: 'light', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#14532d', accentColor: '#22c55e', backgroundColor: '#f7fee7',
    textColor: '#1f2937', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'top-rule', dividerStyle: 'thin',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'soft',
  },
  {
    id: 'sb-card-light', name: 'Small Biz Card', category: 'smallbiz',
    description: 'Mint card, green photo ring, pill contacts',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#14532d', accentColor: '#22c55e', backgroundColor: '#f0fdf4',
    textColor: '#14532d', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 12, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'sb-b-gradient', name: 'Small Biz Banner', category: 'smallbiz',
    description: 'Green gradient banner, white name, clean body',
    layout: 'banner', colorScheme: 'gradient', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#14532d', accentColor: '#22c55e', backgroundColor: '#f7fee7',
    textColor: '#1f2937', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 8, borderStyle: 'none', dividerStyle: 'gradient',
    contactStyle: 'inline', socialStyle: 'icons', shadow: 'soft',
  },

  // ── FREELANCER (5) ─────────────────────────────────────────────────────────
  {
    id: 'fl-h-light', name: 'Freelancer Classic', category: 'freelancer',
    description: 'Indigo + pink, Inter, circle photo — creative freelancer energy',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#312e81', accentColor: '#ec4899', backgroundColor: '#fdf2f8',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'none',
    contactStyle: 'labels', socialStyle: 'buttons', shadow: 'none',
  },
  {
    id: 'fl-h-dark', name: 'Freelancer Dark', category: 'freelancer',
    description: 'Deep indigo, pink accents — vibrant dark freelancer look',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#e0e7ff', accentColor: '#f472b6', backgroundColor: '#1e1b4b',
    textColor: '#e0e7ff', mutedColor: '#a5b4fc', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'buttons', shadow: 'none',
  },
  {
    id: 'fl-v-gradient', name: 'Freelancer Gradient', category: 'freelancer',
    description: 'Indigo-to-pink gradient vertical, white text, bold presence',
    layout: 'vertical', colorScheme: 'gradient', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#312e81', accentColor: '#ec4899', backgroundColor: '#fdf2f8',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 8, borderStyle: 'top-rule', dividerStyle: 'gradient',
    contactStyle: 'stacked', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'fl-card-light', name: 'Freelancer Card', category: 'freelancer',
    description: 'Lavender card, pink photo ring, pill contacts',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#312e81', accentColor: '#ec4899', backgroundColor: '#f5f3ff',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 12, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'fl-split-dark', name: 'Freelancer Split Dark', category: 'freelancer',
    description: 'Indigo left panel, dark right — creative split contrast',
    layout: 'split', colorScheme: 'dark', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#e0e7ff', accentColor: '#f472b6', backgroundColor: '#1e1b4b',
    textColor: '#e0e7ff', mutedColor: '#a5b4fc', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'none',
  },

  // ── CONSULTANT (5) ─────────────────────────────────────────────────────────
  {
    id: 'con-h-light', name: 'Consultant Classic', category: 'consultant',
    description: 'Slate + sky blue, square photo, left rule — strategic and sharp',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'square',
    primaryColor: '#0f172a', accentColor: '#0ea5e9', backgroundColor: '#ffffff',
    textColor: '#0f172a', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'con-h-dark', name: 'Consultant Dark', category: 'consultant',
    description: 'Dark slate, sky-blue accents — premium consulting dark',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'square',
    primaryColor: '#f0f9ff', accentColor: '#38bdf8', backgroundColor: '#0f172a',
    textColor: '#f0f9ff', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'con-v-light', name: 'Consultant Vertical', category: 'consultant',
    description: 'Centred vertical, sky-blue top rule, circle photo',
    layout: 'vertical', colorScheme: 'light', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#0f172a', accentColor: '#0ea5e9', backgroundColor: '#f8fafc',
    textColor: '#0f172a', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'top-rule', dividerStyle: 'thin',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'soft',
  },
  {
    id: 'con-card-light', name: 'Consultant Card', category: 'consultant',
    description: 'Light blue card, sky-blue photo ring, pill contacts',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#0f172a', accentColor: '#0ea5e9', backgroundColor: '#f0f9ff',
    textColor: '#0f172a', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 8, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'con-split-dark', name: 'Consultant Split Dark', category: 'consultant',
    description: 'Dark slate left, white right — authoritative consulting split',
    layout: 'split', colorScheme: 'dark', accentBar: 'none', photoShape: 'square',
    primaryColor: '#f0f9ff', accentColor: '#38bdf8', backgroundColor: '#0f172a',
    textColor: '#f0f9ff', mutedColor: '#64748b', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'none',
  },

  // ── SALES (5) ──────────────────────────────────────────────────────────────
  {
    id: 'sal-h-light', name: 'Sales Classic', category: 'sales',
    description: 'Crimson + red, circle photo, bold left rule — high-energy sales',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#7f1d1d', accentColor: '#ef4444', backgroundColor: '#fff1f2',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'sal-h-dark', name: 'Sales Dark', category: 'sales',
    description: 'Dark crimson, red accents — aggressive sales energy',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#fee2e2', accentColor: '#f87171', backgroundColor: '#450a0a',
    textColor: '#fee2e2', mutedColor: '#fca5a5', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'sal-v-light', name: 'Sales Vertical', category: 'sales',
    description: 'Centred vertical, red top rule, circle photo',
    layout: 'vertical', colorScheme: 'light', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#7f1d1d', accentColor: '#ef4444', backgroundColor: '#fff1f2',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 4, borderStyle: 'top-rule', dividerStyle: 'thin',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'soft',
  },
  {
    id: 'sal-card-light', name: 'Sales Card', category: 'sales',
    description: 'Rose card, red photo ring, pill contacts',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#7f1d1d', accentColor: '#ef4444', backgroundColor: '#fff1f2',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 8, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'sal-b-gradient', name: 'Sales Banner', category: 'sales',
    description: 'Red gradient banner, white name, clean body',
    layout: 'banner', colorScheme: 'gradient', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#7f1d1d', accentColor: '#ef4444', backgroundColor: '#fff1f2',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Arial, Helvetica, sans-serif',
    borderRadius: 8, borderStyle: 'none', dividerStyle: 'gradient',
    contactStyle: 'inline', socialStyle: 'icons', shadow: 'soft',
  },

  // ── EXECUTIVE (6) ──────────────────────────────────────────────────────────
  {
    id: 'exe-h-light', name: 'Executive Classic', category: 'executive',
    description: 'Charcoal + silver, Georgia serif, bottom rule — C-suite authority',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'bottom', photoShape: 'circle',
    primaryColor: '#020617', accentColor: '#a3a3a3', backgroundColor: '#ffffff',
    textColor: '#111827', mutedColor: '#737373', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'bottom-rule', dividerStyle: 'thin',
    contactStyle: 'labels', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'exe-h-dark', name: 'Executive Dark', category: 'executive',
    description: 'Jet black, silver accents, serif — the ultimate executive dark',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'bottom', photoShape: 'circle',
    primaryColor: '#f5f5f5', accentColor: '#d4d4d4', backgroundColor: '#0a0a0a',
    textColor: '#f5f5f5', mutedColor: '#a3a3a3', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'bottom-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'exe-v-light', name: 'Executive Vertical', category: 'executive',
    description: 'Centred serif vertical, silver left rule, square photo',
    layout: 'vertical', colorScheme: 'light', accentBar: 'left', photoShape: 'square',
    primaryColor: '#020617', accentColor: '#a3a3a3', backgroundColor: '#ffffff',
    textColor: '#111827', mutedColor: '#737373', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'left-rule', dividerStyle: 'dotted',
    contactStyle: 'stacked', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'exe-card-light', name: 'Executive Card', category: 'executive',
    description: 'White card, silver photo ring, serif name — boardroom ready',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#020617', accentColor: '#a3a3a3', backgroundColor: '#fafafa',
    textColor: '#111827', mutedColor: '#737373', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 8, borderStyle: 'solid', dividerStyle: 'thin',
    contactStyle: 'pills', socialStyle: 'text', shadow: 'soft',
  },
  {
    id: 'exe-split-dark', name: 'Executive Split Dark', category: 'executive',
    description: 'Black left panel, white right — ultimate executive contrast',
    layout: 'split', colorScheme: 'dark', accentBar: 'none', photoShape: 'square',
    primaryColor: '#f5f5f5', accentColor: '#d4d4d4', backgroundColor: '#0a0a0a',
    textColor: '#f5f5f5', mutedColor: '#a3a3a3', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'stacked', socialStyle: 'text', shadow: 'none',
  },
  {
    id: 'exe-b-light', name: 'Executive Banner', category: 'executive',
    description: 'Charcoal banner, serif name in white, silver contacts',
    layout: 'banner', colorScheme: 'light', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#020617', accentColor: '#a3a3a3', backgroundColor: '#ffffff',
    textColor: '#374151', mutedColor: '#737373', fontFamily: 'Georgia, Times New Roman, serif',
    nameFontFamily: 'Georgia, Times New Roman, serif',
    borderRadius: 0, borderStyle: 'top-rule', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },

  // ── PERSONAL (6) ───────────────────────────────────────────────────────────
  {
    id: 'per-h-light', name: 'Personal Classic', category: 'personal',
    description: 'Indigo + violet, Inter, circle photo — warm and personal',
    layout: 'horizontal', colorScheme: 'light', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#1e1b4b', accentColor: '#8b5cf6', backgroundColor: '#f5f3ff',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'none',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'per-h-dark', name: 'Personal Dark', category: 'personal',
    description: 'Deep indigo, violet accents — personal dark mode',
    layout: 'horizontal', colorScheme: 'dark', accentBar: 'left', photoShape: 'circle',
    primaryColor: '#ede9fe', accentColor: '#a78bfa', backgroundColor: '#1e1b4b',
    textColor: '#ede9fe', mutedColor: '#a78bfa', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 4, borderStyle: 'left-rule', dividerStyle: 'bold',
    contactStyle: 'labels', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'per-v-gradient', name: 'Personal Gradient', category: 'personal',
    description: 'Indigo-to-violet gradient vertical, white text',
    layout: 'vertical', colorScheme: 'gradient', accentBar: 'top', photoShape: 'circle',
    primaryColor: '#1e1b4b', accentColor: '#8b5cf6', backgroundColor: '#f5f3ff',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 8, borderStyle: 'top-rule', dividerStyle: 'gradient',
    contactStyle: 'stacked', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'per-card-light', name: 'Personal Card', category: 'personal',
    description: 'Lavender card, violet photo ring, pill contacts',
    layout: 'card', colorScheme: 'light', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#1e1b4b', accentColor: '#8b5cf6', backgroundColor: '#f5f3ff',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 12, borderStyle: 'solid', dividerStyle: 'none',
    contactStyle: 'pills', socialStyle: 'buttons', shadow: 'soft',
  },
  {
    id: 'per-split-dark', name: 'Personal Split Dark', category: 'personal',
    description: 'Indigo left panel, dark right — personal dark split',
    layout: 'split', colorScheme: 'dark', accentBar: 'none', photoShape: 'circle',
    primaryColor: '#ede9fe', accentColor: '#a78bfa', backgroundColor: '#1e1b4b',
    textColor: '#ede9fe', mutedColor: '#a78bfa', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'stacked', socialStyle: 'icons', shadow: 'none',
  },
  {
    id: 'per-c-light', name: 'Personal Compact', category: 'personal',
    description: 'Compact violet, inline contacts, minimal footprint',
    layout: 'compact', colorScheme: 'minimal', accentBar: 'none', photoShape: 'none',
    primaryColor: '#1e1b4b', accentColor: '#8b5cf6', backgroundColor: '#f5f3ff',
    textColor: '#1f2937', mutedColor: '#6b7280', fontFamily: 'Inter, Arial, sans-serif',
    borderRadius: 0, borderStyle: 'none', dividerStyle: 'none',
    contactStyle: 'inline', socialStyle: 'text', shadow: 'none',
  },
];

export function getTemplateById(id: string): SignatureTemplate | undefined {
  return SIGNATURE_TEMPLATES.find(t => t.id === id);
}

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  'corporate', 'modern', 'minimal', 'creative', 'luxury',
  'tech', 'healthcare', 'legal', 'realestate', 'education',
  'smallbiz', 'freelancer', 'consultant', 'sales', 'executive', 'personal',
];
