// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const coming_soon: { "features": Array<string> };
  export const demo: { "FAQS": Array<{ "q": string; "a": string; "id": string }>; "bars": Array<number> };
  export const home: { "FAQ": Array<{ "q": string; "a": string; "id": string }> };
  export const maintenance: { "updates": Array<string> };
  export const support: { "FAQS": Array<{ "q": string; "a": string; "id": string }> };
}
