/**
 * POST /api/admin/authority-report/generate
 *
 * Generates an Authority & Incident Report PDF.
 * High-risk: requires admin login + PIN + high-risk challenge token.
 *
 * Body: AuthorityReportRequest (see interface below)
 *
 * Every generation, view, and download is written to the audit log.
 */
import type { Request, Response } from 'express';
import { PDFDocument, StandardFonts, rgb, type RGB, type PDFPage, type PDFFont } from 'pdf-lib';
import db from '../../db';
import { writeAudit } from '../../lib/audit.js';

// ── Safe string (WinAnsi only) ────────────────────────────────────────────────
function s(text: string): string {
  return String(text ?? '')
    .replace(/\u2014/g, '-').replace(/\u2013/g, '-').replace(/\u2026/g, '...')
    .replace(/\u2192/g, '->').replace(/\u2018|\u2019/g, "'")
    .replace(/\u201c|\u201d/g, '"').replace(/\u2122/g, '(TM)')
    .replace(/\u00ae/g, '(R)').replace(/\u00a9/g, '(c)')
    .replace(/\u2713|\u2714/g, 'Y').replace(/\u2717|\u2718/g, 'N')
    .replace(/\u2139/g, 'i').replace(/\u26a0/g, '!')
    .replace(/[^\u0000-\u00ff]/g, '?');
}

// ── Colours ───────────────────────────────────────────────────────────────────
const C = {
  navy:   rgb(0.118, 0.227, 0.373),
  brand:  rgb(0.145, 0.380, 0.922),
  dark:   rgb(0.118, 0.161, 0.231),
  muted:  rgb(0.420, 0.447, 0.502),
  light:  rgb(0.949, 0.953, 0.957),
  border: rgb(0.882, 0.894, 0.910),
  white:  rgb(1, 1, 1),
  black:  rgb(0, 0, 0),
  red:    rgb(0.800, 0.200, 0.200),
  amber:  rgb(0.800, 0.600, 0.100),
  green:  rgb(0.133, 0.545, 0.133),
};

// ── Page constants ────────────────────────────────────────────────────────────
const A4W = 595.28;
const A4H = 841.89;
const MARGIN = 56;
const CONTENT_W = A4W - MARGIN * 2;

interface Ctx {
  doc: PDFDocument;
  pages: PDFPage[];
  fontB: PDFFont;
  fontR: PDFFont;
  fontI: PDFFont;
  y: number;
  pageNum: number;
}

function newPage(ctx: Ctx): PDFPage {
  const page = ctx.doc.addPage([A4W, A4H]);
  ctx.pages.push(page);
  ctx.pageNum = ctx.pages.length;
  ctx.y = A4H - MARGIN;
  // Header rule
  page.drawLine({ start: { x: MARGIN, y: A4H - 36 }, end: { x: A4W - MARGIN, y: A4H - 36 }, thickness: 0.5, color: C.border });
  // Header text
  page.drawText(s('Sousa Murray Profiles — Authority & Incident Report'), { x: MARGIN, y: A4H - 28, size: 7, font: ctx.fontR, color: C.muted });
  page.drawText(s(`Page ${ctx.pageNum}`), { x: A4W - MARGIN - 30, y: A4H - 28, size: 7, font: ctx.fontR, color: C.muted });
  // Footer
  page.drawLine({ start: { x: MARGIN, y: 28 }, end: { x: A4W - MARGIN, y: 28 }, thickness: 0.5, color: C.border });
  page.drawText(s('Generated by Sousa Murray Profiles, operated by JA Group Services Ltd. CONFIDENTIAL — RESTRICTED DISTRIBUTION.'), { x: MARGIN, y: 18, size: 6, font: ctx.fontI, color: C.muted });
  return page;
}

function currentPage(ctx: Ctx): PDFPage {
  return ctx.pages[ctx.pages.length - 1];
}

function ensureSpace(ctx: Ctx, needed: number) {
  if (ctx.y - needed < 60) newPage(ctx);
}

function drawText(ctx: Ctx, text: string, opts: { size?: number; font?: PDFFont; color?: RGB; indent?: number; lineHeight?: number }) {
  const size = opts.size ?? 10;
  const font = opts.font ?? ctx.fontR;
  const color = opts.color ?? C.dark;
  const indent = opts.indent ?? 0;
  const lineHeight = opts.lineHeight ?? size * 1.5;
  const maxW = CONTENT_W - indent;

  // Word-wrap
  const words = s(text).split(' ');
  let line = '';
  const lines: string[] = [];
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    const w = font.widthOfTextAtSize(test, size);
    if (w > maxW && line) { lines.push(line); line = word; }
    else line = test;
  }
  if (line) lines.push(line);

  for (const l of lines) {
    ensureSpace(ctx, lineHeight + 2);
    currentPage(ctx).drawText(l, { x: MARGIN + indent, y: ctx.y, size, font, color });
    ctx.y -= lineHeight;
  }
}

function drawH1(ctx: Ctx, text: string) {
  ensureSpace(ctx, 32);
  ctx.y -= 6;
  currentPage(ctx).drawText(s(text), { x: MARGIN, y: ctx.y, size: 16, font: ctx.fontB, color: C.navy });
  ctx.y -= 22;
  currentPage(ctx).drawLine({ start: { x: MARGIN, y: ctx.y }, end: { x: A4W - MARGIN, y: ctx.y }, thickness: 1, color: C.brand });
  ctx.y -= 10;
}

function drawH2(ctx: Ctx, text: string) {
  ensureSpace(ctx, 24);
  ctx.y -= 4;
  currentPage(ctx).drawText(s(text), { x: MARGIN, y: ctx.y, size: 12, font: ctx.fontB, color: C.navy });
  ctx.y -= 18;
}

function drawField(ctx: Ctx, label: string, value: string, highlight?: 'red' | 'amber' | 'green') {
  ensureSpace(ctx, 28);
  const page = currentPage(ctx);
  // Label
  page.drawText(s(label), { x: MARGIN, y: ctx.y, size: 8, font: ctx.fontB, color: C.muted });
  ctx.y -= 13;
  // Value background
  const valueColor = highlight === 'red' ? C.red : highlight === 'amber' ? C.amber : highlight === 'green' ? C.green : C.dark;
  drawText(ctx, value || '(not provided)', { size: 10, color: valueColor, indent: 0 });
  ctx.y -= 4;
}

function drawWarningBox(ctx: Ctx, text: string) {
  ensureSpace(ctx, 50);
  const page = currentPage(ctx);
  page.drawRectangle({ x: MARGIN, y: ctx.y - 36, width: CONTENT_W, height: 40, color: rgb(1, 0.97, 0.88), borderColor: C.amber, borderWidth: 1 });
  page.drawText(s('! IMPORTANT'), { x: MARGIN + 8, y: ctx.y - 10, size: 8, font: ctx.fontB, color: C.amber });
  drawText(ctx, text, { size: 8, color: C.dark, indent: 8 });
  ctx.y -= 8;
}

function drawDivider(ctx: Ctx) {
  ensureSpace(ctx, 12);
  ctx.y -= 4;
  currentPage(ctx).drawLine({ start: { x: MARGIN, y: ctx.y }, end: { x: A4W - MARGIN, y: ctx.y }, thickness: 0.3, color: C.border });
  ctx.y -= 8;
}

function drawCheckedSections(ctx: Ctx, sections: string[]) {
  for (const sec of sections) {
    ensureSpace(ctx, 16);
    currentPage(ctx).drawText(s(`[Y] ${sec}`), { x: MARGIN + 8, y: ctx.y, size: 9, font: ctx.fontR, color: C.dark });
    ctx.y -= 14;
  }
}

// ── Report types ──────────────────────────────────────────────────────────────
export const REPORT_TYPES = [
  'Internal incident report',
  'Profile report summary',
  'User report summary',
  'Abuse/safety report',
  'Fraud/security report',
  'Police/authority request report',
  'Court/legal request report',
  'Safeguarding concern report',
  'Data disclosure decision record',
] as const;

export type ReportType = typeof REPORT_TYPES[number];

export interface AuthorityReportRequest {
  // Core
  reportType: ReportType;
  reason: string;
  useType: 'internal' | 'external';
  // External authority details
  authorityName?: string;
  officerName?: string;
  contactEmail?: string;
  contactPhone?: string;
  caseReference?: string;
  requestDate?: string;
  deadline?: string;
  legalBasis?: string;
  requestType?: 'court_order' | 'warrant' | 'statutory' | 'voluntary' | 'other';
  // Subject
  subjectUserId?: number;
  subjectProfileId?: number;
  // Data decisions
  informationRequested: string;
  informationIncluded: string;
  informationWithheld: string;
  adminDecisionNote: string;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  urgentRisk: boolean;
  // Sections to include
  sections: string[];
}

// ── Reference number generator ────────────────────────────────────────────────
function generateRef(): string {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  const rand = Math.random().toString(36).substring(2, 7).toUpperCase();
  return `JAR-${y}${m}${d}-${rand}`;
}

// ── Main handler ──────────────────────────────────────────────────────────────
export async function generateAuthorityReport(req: Request, res: Response) {
  const adminId = (req as any).session?.adminUserId;
  const adminUser = adminId
    ? (db.prepare("SELECT id, name, email FROM users WHERE id = ? AND role = 'admin'").get(adminId) as { id: number; name: string; email: string } | undefined)
    : undefined;

  const adminName  = adminUser?.name  ?? 'Unknown Admin';
  const adminEmail = adminUser?.email ?? 'unknown';

  const body = req.body as AuthorityReportRequest;

  // ── Validation ────────────────────────────────────────────────────────────
  if (!body.reportType || !REPORT_TYPES.includes(body.reportType)) {
    return res.status(400).json({ success: false, error: 'Invalid or missing reportType' });
  }
  if (!body.reason?.trim()) {
    return res.status(400).json({ success: false, error: 'reason is required' });
  }
  if (!body.informationRequested?.trim()) {
    return res.status(400).json({ success: false, error: 'informationRequested is required' });
  }
  if (!body.informationIncluded?.trim()) {
    return res.status(400).json({ success: false, error: 'informationIncluded is required' });
  }
  if (!body.adminDecisionNote?.trim()) {
    return res.status(400).json({ success: false, error: 'adminDecisionNote is required' });
  }
  if (!Array.isArray(body.sections) || body.sections.length === 0) {
    return res.status(400).json({ success: false, error: 'At least one section must be selected' });
  }

  const reportRef = generateRef();
  const generatedAt = new Date().toISOString();

  // ── Audit: generation started ─────────────────────────────────────────────
  writeAudit({
    actorId: adminId, actorName: adminName, actorEmail: adminEmail,
    actorType: 'admin', tenant: 'admin_workforce', authProvider: 'microsoft_entra_workforce',
    action: 'authority_report_generate',
    resourceType: 'authority_report',
    resourceLabel: reportRef,
    details: `Authority report generated. Type: ${body.reportType}. Use: ${body.useType}. Risk: ${body.riskLevel}. Sections: ${body.sections.join(', ')}. Reason: ${body.reason}`,
    ipAddress: req.ip,
    userAgent: req.headers['user-agent'] ?? null,
    result: 'success',
  });

  // ── Fetch subject data if provided ────────────────────────────────────────
  let subjectUser: { id: number; name: string; email: string; role: string; plan_id: number | null; created_at: string; account_status: string | null; user_number: string | null } | undefined;
  let subjectProfile: { id: number; username: string; display_name: string | null; created_at: string } | undefined;
  let auditEntries: { action: string; created_at: string; details: string | null; result: string }[] = [];
  let supportTickets: { id: number; subject: string; status: string; created_at: string }[] = [];
  let adminNotes: { note: string; admin_name: string; created_at: string }[] = [];

  if (body.subjectUserId && body.sections.some(s => ['Reported user account summary', 'Admin notes', 'Audit log entries', 'Support tickets linked to the report'].includes(s))) {
    subjectUser = db.prepare(
      "SELECT id, name, email, role, plan_id, created_at, account_status, user_number FROM users WHERE id = ?"
    ).get(body.subjectUserId) as typeof subjectUser;

    if (body.sections.includes('Audit log entries')) {
      auditEntries = db.prepare(
        "SELECT action, created_at, details, result FROM audit_log WHERE resource_id = ? OR actor_id = ? ORDER BY created_at DESC LIMIT 50"
      ).all(String(body.subjectUserId), body.subjectUserId) as typeof auditEntries;
    }

    if (body.sections.includes('Support tickets linked to the report')) {
      supportTickets = db.prepare(
        "SELECT id, subject, status, created_at FROM support_requests WHERE user_id = ? ORDER BY created_at DESC LIMIT 20"
      ).all(body.subjectUserId) as typeof supportTickets;
    }

    if (body.sections.includes('Admin notes')) {
      adminNotes = db.prepare(
        "SELECT note, admin_name, created_at FROM admin_user_notes WHERE user_id = ? ORDER BY created_at DESC LIMIT 20"
      ).all(body.subjectUserId) as typeof adminNotes;
    }
  }

  if (body.subjectProfileId && body.sections.includes('Reported profile details')) {
    subjectProfile = db.prepare(
      "SELECT id, username, display_name, created_at FROM profiles WHERE id = ?"
    ).get(body.subjectProfileId) as typeof subjectProfile;
  }

  // ── Build PDF ─────────────────────────────────────────────────────────────
  const doc = await PDFDocument.create();
  const fontB  = await doc.embedFont(StandardFonts.HelveticaBold);
  const fontR  = await doc.embedFont(StandardFonts.Helvetica);
  const fontI  = await doc.embedFont(StandardFonts.HelveticaOblique);

  const ctx: Ctx = { doc, pages: [], fontB, fontR, fontI, y: 0, pageNum: 0 };

  // ── Cover page ────────────────────────────────────────────────────────────
  const cover = doc.addPage([A4W, A4H]);
  ctx.pages.push(cover);
  ctx.pageNum = 1;
  ctx.y = A4H - MARGIN;

  // Cover header band
  cover.drawRectangle({ x: 0, y: A4H - 120, width: A4W, height: 120, color: C.navy });
  cover.drawText(s('AUTHORITY & INCIDENT REPORT'), { x: MARGIN, y: A4H - 55, size: 20, font: fontB, color: C.white });
  cover.drawText(s('Sousa Murray Profiles — Operated by JA Group Services Ltd'), { x: MARGIN, y: A4H - 78, size: 10, font: fontR, color: rgb(0.7, 0.8, 1) });

  // Classification band
  const isExternal = body.useType === 'external';
  const classColor = isExternal ? C.red : C.amber;
  cover.drawRectangle({ x: 0, y: A4H - 145, width: A4W, height: 25, color: classColor });
  cover.drawText(s(isExternal ? 'EXTERNAL — RESTRICTED DISTRIBUTION' : 'INTERNAL — STAFF USE ONLY'), { x: MARGIN, y: A4H - 137, size: 10, font: fontB, color: C.white });

  ctx.y = A4H - 175;

  // Cover fields
  const coverFields: [string, string][] = [
    ['Report Reference',  reportRef],
    ['Report Type',       body.reportType],
    ['Generated',         new Date(generatedAt).toLocaleString('en-GB', { timeZone: 'Europe/London' })],
    ['Generated By',      `${adminName} (${adminEmail})`],
    ['Product',           'Sousa Murray Profiles'],
    ['Operator',          'JA Group Services Ltd'],
    ['Use',               isExternal ? 'External' : 'Internal'],
    ['Risk Level',        body.riskLevel.toUpperCase()],
    ['Urgent Risk',       body.urgentRisk ? 'YES — URGENT RISK FLAGGED' : 'No'],
  ];

  for (const [label, value] of coverFields) {
    ensureSpace(ctx, 22);
    const page = currentPage(ctx);
    page.drawText(s(label + ':'), { x: MARGIN, y: ctx.y, size: 9, font: fontB, color: C.muted });
    const valColor = label === 'Risk Level' && (body.riskLevel === 'high' || body.riskLevel === 'critical') ? C.red
      : label === 'Urgent Risk' && body.urgentRisk ? C.red : C.dark;
    page.drawText(s(value), { x: MARGIN + 140, y: ctx.y, size: 9, font: fontR, color: valColor });
    ctx.y -= 16;
  }

  ctx.y -= 10;
  // Compliance warning
  cover.drawRectangle({ x: MARGIN, y: ctx.y - 52, width: CONTENT_W, height: 56, color: rgb(1, 0.97, 0.88), borderColor: C.amber, borderWidth: 1 });
  cover.drawText(s('COMPLIANCE NOTICE'), { x: MARGIN + 8, y: ctx.y - 10, size: 8, font: fontB, color: C.amber });
  const complianceText = s('Only disclose personal data where JA Group Services Ltd has a lawful basis and the disclosure is necessary and proportionate. If unsure, seek legal/data protection advice before disclosure. This system documents the decision — it does not make it.');
  const compWords = complianceText.split(' ');
  let compLine = '';
  const compLines: string[] = [];
  for (const w of compWords) {
    const test = compLine ? `${compLine} ${w}` : w;
    if (fontR.widthOfTextAtSize(test, 8) > CONTENT_W - 16 && compLine) { compLines.push(compLine); compLine = w; }
    else compLine = test;
  }
  if (compLine) compLines.push(compLine);
  let cy = ctx.y - 22;
  for (const l of compLines) {
    cover.drawText(l, { x: MARGIN + 8, y: cy, size: 8, font: fontI, color: C.dark });
    cy -= 11;
  }
  ctx.y -= 62;

  // Footer on cover
  cover.drawLine({ start: { x: MARGIN, y: 28 }, end: { x: A4W - MARGIN, y: 28 }, thickness: 0.5, color: C.border });
  cover.drawText(s('Generated by Sousa Murray Profiles, operated by JA Group Services Ltd. CONFIDENTIAL — RESTRICTED DISTRIBUTION.'), { x: MARGIN, y: 18, size: 6, font: fontI, color: C.muted });

  // ── Page 2+: Report body ──────────────────────────────────────────────────
  newPage(ctx);

  // ── Section: Report Summary ───────────────────────────────────────────────
  if (body.sections.includes('Report summary')) {
    drawH1(ctx, '1. Report Summary');
    drawField(ctx, 'Report Reference', reportRef);
    drawField(ctx, 'Report Type', body.reportType);
    drawField(ctx, 'Use', isExternal ? 'External' : 'Internal');
    drawField(ctx, 'Risk Level', body.riskLevel.toUpperCase(), body.riskLevel === 'critical' || body.riskLevel === 'high' ? 'red' : body.riskLevel === 'medium' ? 'amber' : 'green');
    drawField(ctx, 'Urgent Risk', body.urgentRisk ? 'YES — URGENT RISK FLAGGED' : 'No', body.urgentRisk ? 'red' : undefined);
    drawField(ctx, 'Reason for Report', body.reason);
    drawField(ctx, 'Generated By', `${adminName} (${adminEmail})`);
    drawField(ctx, 'Generated At', new Date(generatedAt).toLocaleString('en-GB', { timeZone: 'Europe/London' }));
    drawDivider(ctx);
  }

  // ── Section: Authority / External Request Details ─────────────────────────
  if (isExternal) {
    drawH1(ctx, '2. Authority / External Request Details');
    drawWarningBox(ctx, 'Only disclose personal data where JA Group Services Ltd has a lawful basis and the disclosure is necessary and proportionate. If unsure, seek legal/data protection advice before disclosure.');
    drawField(ctx, 'Authority / Body Name', body.authorityName ?? '(not provided)');
    drawField(ctx, 'Officer / Contact Name', body.officerName ?? '(not provided)');
    drawField(ctx, 'Contact Email', body.contactEmail ?? '(not provided)');
    drawField(ctx, 'Contact Phone', body.contactPhone ?? '(not provided)');
    drawField(ctx, 'Case / Reference Number', body.caseReference ?? '(not provided)');
    drawField(ctx, 'Request Date', body.requestDate ?? '(not provided)');
    drawField(ctx, 'Deadline', body.deadline ?? '(not provided)');
    drawField(ctx, 'Legal Basis / Request Type', body.legalBasis ?? '(not provided)');
    const rtLabels: Record<string, string> = {
      court_order: 'Court Order', warrant: 'Warrant', statutory: 'Statutory Request',
      voluntary: 'Voluntary Disclosure', other: 'Other',
    };
    drawField(ctx, 'Request Category', body.requestType ? rtLabels[body.requestType] ?? body.requestType : '(not provided)');
    drawDivider(ctx);
  }

  // ── Section: Subject User ─────────────────────────────────────────────────
  if (body.sections.includes('Reported user account summary') && subjectUser) {
    drawH1(ctx, '3. Subject User Account');
    if (subjectUser.user_number) {
      drawField(ctx, 'Sousa Murray Profiles User Number', subjectUser.user_number.replace(/(\d{3})(\d{3})(\d{3})(\d{3})/, '$1 $2 $3 $4'));
    }
    drawField(ctx, 'Internal Account ID', String(subjectUser.id));
    drawField(ctx, 'Name', subjectUser.name);
    drawField(ctx, 'Email', subjectUser.email);
    drawField(ctx, 'Role', subjectUser.role);
    drawField(ctx, 'Account Status', subjectUser.account_status ?? 'active');
    drawField(ctx, 'Registered', subjectUser.created_at);
    drawDivider(ctx);
  }

  // ── Section: Subject Profile ──────────────────────────────────────────────
  if (body.sections.includes('Reported profile details') && subjectProfile) {
    drawH1(ctx, '4. Subject Profile');
    drawField(ctx, 'Profile ID', String(subjectProfile.id));
    drawField(ctx, 'Username', subjectProfile.username);
    drawField(ctx, 'Display Name', subjectProfile.display_name ?? '(none)');
    drawField(ctx, 'Created', subjectProfile.created_at);
    drawDivider(ctx);
  }

  // ── Section: Data Decisions ───────────────────────────────────────────────
  drawH1(ctx, '5. Data Disclosure Decision');
  drawField(ctx, 'Information Requested', body.informationRequested);
  drawField(ctx, 'Information Included in This Report', body.informationIncluded);
  drawField(ctx, 'Information Withheld', body.informationWithheld || '(none withheld)');
  drawField(ctx, 'Admin Decision Note', body.adminDecisionNote);
  drawDivider(ctx);

  // ── Section: Sections included ────────────────────────────────────────────
  drawH2(ctx, 'Sections Included in This Report');
  drawCheckedSections(ctx, body.sections);
  drawDivider(ctx);

  // ── Section: Admin Notes ──────────────────────────────────────────────────
  if (body.sections.includes('Admin notes') && adminNotes.length > 0) {
    drawH1(ctx, '6. Admin Notes');
    for (const note of adminNotes) {
      drawText(ctx, `[${note.created_at}] ${note.admin_name}: ${note.note}`, { size: 9, indent: 8 });
      ctx.y -= 4;
    }
    drawDivider(ctx);
  }

  // ── Section: Audit Log ────────────────────────────────────────────────────
  if (body.sections.includes('Audit log entries') && auditEntries.length > 0) {
    drawH1(ctx, '7. Audit Log Entries (Subject)');
    for (const entry of auditEntries) {
      ensureSpace(ctx, 20);
      drawText(ctx, `[${entry.created_at}] ${entry.action} — ${entry.result}${entry.details ? ': ' + entry.details : ''}`, { size: 8, indent: 8 });
      ctx.y -= 2;
    }
    drawDivider(ctx);
  }

  // ── Section: Support Tickets ──────────────────────────────────────────────
  if (body.sections.includes('Support tickets linked to the report') && supportTickets.length > 0) {
    drawH1(ctx, '8. Support Tickets');
    for (const ticket of supportTickets) {
      drawText(ctx, `#${ticket.id} — ${ticket.subject} [${ticket.status}] — ${ticket.created_at}`, { size: 9, indent: 8 });
      ctx.y -= 4;
    }
    drawDivider(ctx);
  }

  // ── Section: Actions taken ────────────────────────────────────────────────
  if (body.sections.includes('Actions already taken')) {
    drawH1(ctx, '9. Actions Already Taken');
    drawText(ctx, '(Admin to complete — list any moderation, suspension, or other actions already applied to this account or profile.)', { size: 9, color: C.muted, indent: 8 });
    drawDivider(ctx);
  }

  // ── Section: Evidence list ────────────────────────────────────────────────
  if (body.sections.includes('Evidence/attachments list')) {
    drawH1(ctx, '10. Evidence / Attachments List');
    drawText(ctx, '(Admin to complete — list any screenshots, files, or other evidence attached to or referenced by this report.)', { size: 9, color: C.muted, indent: 8 });
    drawDivider(ctx);
  }

  // ── Section: Legal disclosure decision ───────────────────────────────────
  if (body.sections.includes('Legal disclosure decision')) {
    drawH1(ctx, '11. Legal Disclosure Decision');
    drawWarningBox(ctx, 'Only disclose personal data where JA Group Services Ltd has a lawful basis and the disclosure is necessary and proportionate. If unsure, seek legal/data protection advice before disclosure. This document records the decision — it does not authorise it.');
    drawField(ctx, 'Lawful Basis Relied On', body.legalBasis ?? '(not specified)');
    drawField(ctx, 'Necessity & Proportionality Assessment', body.adminDecisionNote);
    drawField(ctx, 'Approved By', `${adminName} (${adminEmail})`);
    drawField(ctx, 'Approval Date/Time', new Date(generatedAt).toLocaleString('en-GB', { timeZone: 'Europe/London' }));
    drawDivider(ctx);
  }

  // ── Final page: signature block ───────────────────────────────────────────
  ensureSpace(ctx, 120);
  ctx.y -= 20;
  drawH2(ctx, 'Report Certification');
  drawText(ctx, `This report was generated by ${adminName} (${adminEmail}) on ${new Date(generatedAt).toLocaleString('en-GB', { timeZone: 'Europe/London' })}.`, { size: 9 });
  drawText(ctx, `Report Reference: ${reportRef}`, { size: 9 });
  drawText(ctx, 'This document is confidential and intended solely for the named recipient(s). Unauthorised disclosure, copying, or distribution is prohibited.', { size: 8, color: C.muted });
  ctx.y -= 20;
  currentPage(ctx).drawLine({ start: { x: MARGIN, y: ctx.y }, end: { x: MARGIN + 200, y: ctx.y }, thickness: 0.5, color: C.dark });
  ctx.y -= 14;
  drawText(ctx, 'Authorised Signature / Admin', { size: 8, color: C.muted });

  // ── Serialise ─────────────────────────────────────────────────────────────
  const pdfBytes = await doc.save();

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="authority-report-${reportRef}.pdf"`);
  res.setHeader('X-Report-Ref', reportRef);
  res.send(Buffer.from(pdfBytes));
}
